language: node_js
node_js:
  - "6.5"
install:
  - npm install -g firebase-tools
  - npm install -g angular-cli
  - npm install --no-optional
script:
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN